gibson.lo: /home/evilsocket/Desktop/Dev/phpgibson/gibson.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/evilsocket/Desktop/Dev/phpgibson $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/evilsocket/Desktop/Dev/phpgibson/gibson.c -o gibson.lo 
$(phplibdir)/gibson.la: ./gibson.la
	$(LIBTOOL) --mode=install cp ./gibson.la $(phplibdir)

./gibson.la: $(shared_objects_gibson) $(GIBSON_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_gibson) $(GIBSON_SHARED_LIBADD)

